import json
import os

BASE_DIR = r"d:\idontknow\dotabyss-translation\translations\novels"

data_12 = {
    "スルリと試着中の娼館衣装をはだけると、豊かなコトノの胸が露わになる。<br>それが恥ずかしいのか、コトノの頬が紅潮していく。": "Khi nhẹ nhàng gạt lớp trang phục kỹ viện đang mặc thử ra, bộ ngực đẫy đà của Kotono liền lộ ra.<br>Có lẽ vì ngượng ngùng nên đôi má Kotono chợt ửng hồng.",
    "や、やはり恥ずかしいものですね……<br>殿方に裸を見られるというのは……": "Q-Quả nhiên vẫn thấy ngượng quá……<br>Khi bị nam nhân nhìn thấy thân thể trần trụi thế này……",
    "コトノは耳としっぽをフルフルと震わせている。<br>こんなに弱々しく見えるコトノは初めてだった。": "Đôi tai và chiếc đuôi của Kotono khẽ run rẩy.<br>Đây là lần đầu tiên tôi thấy một Kotono trông yếu đuối đến vậy.",
    "実は私……胸が大きいことが、凄く恥ずかしくて……<br>普段はサラシを巻いて押さえつけているんです……": "Thực ra tại hạ…… luôn thấy rất xấu hổ vì ngực mình quá to……<br>Thường ngày toàn phải dùng vải quấn chặt ép lại……",
    "普段は兵士たちを相手に、激しい稽古を付けている勇ましいコトノである。<br>そんな彼女がこんなに恥じらう姿はとても新鮮だった。": "Bình thường Kotono luôn oai phong lẫm liệt khi huấn luyện nghiêm khắc cho các binh sĩ.<br>Dáng vẻ thẹn thùng này của cô ấy mang lại cảm giác thật mới mẻ.",
    "そのギャップのせいか、衝動的に下腹部がみるみると膨張していく。<br>排そしてすぐにもう抑えきれないほどになっていた。": "Chính sự tương phản ấy đã kích thích dục vọng khiến vùng bụng dưới của tôi nhanh chóng cuồn cuộn phồng lên.<br>Chẳng mấy chốc nó đã lớn đến mức không thể kiềm chế nổi nữa.",
    "ひぃっ！？　えええぇっ！？": "Hii!? Ehh!?",
    "隆々と屹立した陰茎が、コトノの目の前に晒されると、<br>彼女は目を見開いてそれを見つめる。": "Khi dương vật cuồn cuộn giương cao lộ ra ngay trước mắt Kotono,<br>cô ấy mở to mắt nhìn chằm chằm vào nó.",
    "と、殿方のモノが、こ、こんなに……大きなものだとは……": "C-Của nam nhân…… lại…… to lớn nhường này sao……",
    "コトノのリアクションを見て、男性器を見るのが初めてなのか聞いてみる。": "Thấy phản ứng của Kotono, tôi liền hỏi liệu đây có phải lần đầu cô ấy nhìn thấy bộ phận sinh dục nam.",
    "い、いえ、初めてだと言うわけではないのですが、<br>見たことあると言っても、幼い弟のものくらいでして……": "K-Không, không hẳn là lần đầu tiên ạ……<br>Nhưng dù có từng thấy thì cũng chỉ là của đứa em trai còn nhỏ thôi……",
    "そ、想像以上の大きさですね……<br>こんなに大きなもの……ほ、本当に、私の中に入るのでしょうか……？": "N-Nó to hơn tưởng tượng nhiều quá……<br>Thứ to thế này…… liệu h-hoàn toàn có thể vào trong cơ thể tại hạ được sao……?",
    "しっかり準備しておけば大丈夫だ、と彼女の不安を拭うように<br>優しく声を掛ける。": "Tôi ân cần trấn an để xua tan nỗi lo lắng của cô ấy rằng chỉ cần chuẩn bị kỹ càng là sẽ ổn thôi.",
    "はぁうっ……！　んんぅっ……んぁあぁっ……♡": "Hà uuu……! Hừm…… hở aaa……♡",
    "陰茎を膣口に擦りつけると、コトノは耳をピクピクと動かしながら<br>甘い嬌声を上げる。": "Khi tôi cạ dương vật vào cửa mình, đôi tai Kotono khẽ giật giật<br>cùng lúc thốt lên những tiếng kiều mị ngọt ngào.",
    "ん……んんっ、ぅうんっ……んく……んはぁぁっ♡<br>わ、私としたことが……へ、変な声が出て……んっ……あぁっ♡": "Ưm…… hừm, ừm…… hức…… hà aa……♡<br>T-Tại hạ thật là…… lại phát ra âm thanh kỳ quặc thế này…… ưm…… aa……♡",
    "やぁ、んっ……はぁぁっ♡<br>だ、旦那様のモノ……す、すごく熱い……！　んっ、んんん……っ！": "A, ưm…… hà aa♡<br>C-Của Tướng công…… r-rất nóng……! Ưm, hừm……!",
    "声が出るのが恥ずかしいのか、コトノは声を抑えるのに必死なようだ。<br>だがピクピクと震えるその耳としっぽが声以上に雄弁に反応してしまっていた。": "Có lẽ vì ngượng khi phát ra tiếng nên Kotono cố hết sức kìm nén tiếng rên.<br>Thế nhưng đôi tai và chiếc đuôi khẽ run rẩy lại phản ứng chân thực hơn cả lời nói.",
    "旦那、様……あっ、あぁ、私……ヘンです……<br>さっきから、変な声が出ちゃって……んっ、んっ、っあぁ……！": "Tướng công…… a, aa, tại hạ…… lạ lắm……<br>Từ nãy đến giờ cứ phát ra âm thanh kỳ quái…… ưm, ưm, aa……!",
    "声が出ることは変なことではない、と教えてやる。": "Tôi bảo với cô ấy rằng phát ra tiếng rên chẳng có gì là kỳ lạ cả.",
    "で、でも……こんな声……は、恥ずかしくて……<br>はぅっ……んっ、んぅぅ……っ、あっ……あはぁっ……！": "N-Nhưng mà…… tiếng rên này…… t-thấy xấu hổ lắm……<br>Hà uuu…… ưm, hừm…… a…… hà aa……!",
    "コトノは潤んだ瞳でこちらを見上げた。<br>その目を見つめ返しながら、さらに入口を強く擦り上げてやる。": "Kotono ngước nhìn tôi bằng đôi mắt ướt đẫm.<br>Đáp lại ánh mắt ấy, tôi càng ấn cạ mạnh hơn vào lối vào.",
    "はぅ……あぁぁぁっ♡<br>だ、旦那様……準備って、い、いつまで続けるんですか……！？": "Hà uuu…… a aaa♡<br>T-Tướng công…… việc chuẩn bị…… b-bao giờ mới xong vậy ạ……!?",
    "旦那様……もう、私……もう……ああっ、んっ……んんっ♡<br>私、な、なんだか……とても……へ、変な気分になってきちゃって……": "Tướng công…… tại hạ…… không chịu nổi nữa rồi…… a, ưm…… hừm♡<br>Tại hạ c-cảm thấy…… cơ thể cứ…… r-rất kỳ lạ……",
    "擦れ合う秘部の間は、愛液と我慢汁で潤滑油のようにグッショリと濡れている。<br>コトノの秘唇は、すでに受け入れる準備が出来上がっているようだ。": "Giữa chỗ riêng tư ma sát với nhau đã đẫm ướt dâm dịch và dịch rỉ ra như chất bôi trơn.<br>Bờ唇 thầm kín của Kotono xem ra đã sẵn sàng đón nhận.",
    "はぁっ……はぁっ……んんっ……<br>はぐッ……あ、あぁあぁっ……！　やっ……！　はぁああぁぁぁ……っ！": "Hà…… hà…… hừm……<br>Hặc…… a, a aa……! Đừng……! Hà a aaa……!",
    "硬い異物が侵入してくる初めての感触に、コトノはたまらず声を上げる。<br>耳としっぽもピンと立ち、強い快感を感じているのがわかった。": "Lần đầu tiên cảm nhận được một vật thể cứng rắn xâm nhập vào bên trong, Kotono không kiềm được rên lên thành tiếng.<br>Đôi tai và chiếc đuôi dựng đứng cho thấy cô ấy đang cảm nhận khoái cảm dữ dội.",
    "あぁ……入ってます……わ、私のお腹の奥まで……<br>んっく、はぁあっ……♡　": "Aa…… vào rồi…… s-sâu tận trong bụng tại hạ rồi……<br>Hức, hà a……♡",
    "すごい……あ、あんなに大きなものが、私の中に……<br>熱い……、私のお腹の中……す、すごく熱いです……": "Tuyệt quá…… t-thứ to lớn thế này lại ở trong người tại hạ……<br>Nóng quá…… bên trong bụng tại hạ…… r-rất nóng……",
    "初めてで痛みもあるのだろうが、コトノはそれでも嬉しそうだ。<br>そのキツすぎる蜜壺も、次第に肉棒に馴染んでくる気がする。": "Dù là lần đầu chắc hẳn có chút đau đớn, nhưng Kotono trông vẫn rất hạnh phúc.<br>Huyệt mật quá chật hẹp ấy dường như đang dần thích nghi với dương vật.",
    "コトノに、痛くないのか聞いてみる。": "Tôi hỏi Kotono xem có bị đau không.",
    "いえ、最初は稲妻に打たれたような刺激が走りましが、<br>今は何ともありません……": "Không ạ, ban đầu cứ như có dòng điện xé dọc qua, <br>nhưng giờ thì tại hạ không sao nữa rồi……",
    "あの……このまま動かすの……ですよね？<br>どうぞ遠慮なさらず……旦那様の好きにしてください……": "Chuyện là…… tiếp theo ngài sẽ cử động…… đúng không ạ?<br>Xin ngài cứ tự nhiên…… làm theo ý Tướng công thích đi ạ……",
    "コトノの瞳には、すでにその先の行為への好奇心が浮かんでいた。<br>それならと、コトノの反応を見ながらゆっくりと腰を動かし始める。": "Ánh mắt Kotono đã hiện lên sự tò mò về hành vi tiếp theo.<br>Đã vậy, tôi bắt đầu chậm rãi nhấp hông trong lúc quan sát phản ứng của cô ấy.",
    "はっ、んっ、くふぅっ……、はぁっ……ぁあッ……<br>んんっ……ぁあっ……、っんん……あ、あぁっ……♡": "Hả, ưm, khù uuu…… hà…… a……<br>Hừm…… a…… hừm…… a, aa……♡",
    "んんっ……あぁっ♡　な、何……これ……！？<br>ひぐっ、んっ、あぁ……奥にコツコツ、当たって……はぅうんっ♡": "Hừm…… aa♡ C-Cái gì…… thế này……!?<br>Hức, ưm, aa…… cứ thúc cọc cọc vào sâu bên trong…… hà uuu♡",
    "亀頭が子宮口に届く度、豊満な胸が大きく揺れる。<br>頭の耳はピクピクと震え、今は躊躇なく大きな嬌声を上げている。": "Mỗi lần quy頭 chạm vào cửa tử cung, khuôn ngực đẫy đà lại rung nảy dữ dội.<br>Đôi tai trên đầu khẽ giật giật, giờ đây cô ấy rên cất tiếng kiều mị rên文字人 to không chút ngần ngại.",
    "あぁ、すごい、です……やっ……こ、これっ、すごく……気持ち……いぃ♡<br>あぁっ♡　んっ……あっ、ハァッ……あっ、ぁあぁっ……！": "Aa, tuyệt quá…… c-cái này…… r-rất…… sướng……♡<br>Aa♡ Ưm…… a, hà…… a, a aa……!",
    "んっ、はぁっ……あぁっ……あっ♡<br>あぁ、おかしく、なりそうです………んんっ！　んっ……あああっ♡": "Ưm, hà…… aa…… a♡<br>Aa, sắp điên mất rồi…… hừm! Ưm…… a aa♡",
    "旦那様っ……はぁっ……あぁっ……あっ♡<br>んんっ……ど、どうしていいのか分からないくらい……気持ちいぃ……っ！": "Tướng công…… hà…… aa…… a♡<br>Hừm…… sướng đến mức t-tại hạ không biết phải làm sao nữa……!",
    "（私としたことが、本当にどうしてしまったんだろう……？　<br>思考が……お、おかしくなっちゃってる……）": "(Tại hạ bị làm sao thế này……? <br>Suy nghĩ…… s-sắp rối tung lên rồi……)",
    "（もっと旦那様に卑猥なことをして欲しい……<br>そんな、はしたない欲求が抑えられないでいる……）": "(Muốn Tướng công làm nhiều chuyện dâm ô hơn nữa với mình…… <br>Ham muốn hư hỏng ấy chẳng thể nào kìm hãm lại được……)",
    "あぁっ……♡　だ、旦那様……も、もっと激しくしてください！<br>お、お願い……も、もっと……！": "Aa……♡ T-Tướng công…… h-mạnh hơn nữa đi ạ!<br>X-Xin ngài…… nữa đi……!",
    "コトノの要求通り、腰の動きをさらに速くしてやる。": "Đúng theo yêu cầu của Kotono, tôi gia tăng nhịp nhấp hông nhanh hơn nữa.",
    "んんっ……あっ♡　ぁあああぁっ！　やっ……んぐっ、んん……っ！<br>す、すごいっ……あっ！　あぅ、あんっ、あぁぁっ、はぅぅぅぅ！": "Hừm…… a♡ A a aa! Đừng…… hức, hừm……!<br>T-Tuyệt quá…… a! A u, a ưm, a aa, hà uuuu!",
    "んっ……んんぅっ！　あっ……ぁあっ、んっ……あはぁっ！<br>ぅうんっ……！　あっ、あっ、あっ、んっ……ああぁっ♡": "Ưm…… hừm! A…… a a, ưm…… a hà!<br>Ưm……! A, a, a, ưm…… a aa♡",
    "ひぐっ、んぐっ……あぁぁぁぁぁぁっ♡<br>旦那様……、き、気持ちいいです……！　も、もっと……あぁあっ♡": "Hức, hức…… a a a a a aa♡<br>Tướng công…… s-sướng quá……! Nữa đi…… a aa♡",
    "あぅ！　あんっ！　ああっ、んっく、ひぐっ！　ひゃうっ、あぁぁ……っ♡<br>やっ……き、気持ちよすぎて……あ、頭の中が……壊れてしまいそう……！": "A u! A ưm! A aa, hức, hức! Hơ u, a aa……♡<br>Đừng…… s-sướng quá…… đ-đầu óc tại hạ…… như hỏng mất rồi……!",
    "（か、身体に力が入らない……こんなに無防備な姿を晒していると<br>いうのに、私、すごく興奮しちゃってる……）": "(Thân thể không còn chút sức lực nào…… Dù đang để lộ tư thế hoàn toàn không chút phòng bị thế này, <br>mình lại cảm thấy cực kỳ hưng phấn……)",
    "膣肉がわなないて激しくうねり、結合部から白く泡立った飛沫がこぼれる。<br>もうコトノの絶頂が近い証拠だ。": "Thịt âm đạo run rẩy co bóp dữ dội, nơi giao hợp trào ra bọt trắng xóa.<br>Đó là bằng chứng cho thấy Kotono đã tiến rất gần đến đỉnh điểm.",
    "んぐっ、あああぁっ♡　だめ、です……私、頭の中に……な、何かが来てる！<br>わ……私、本当におかしくなっちゃいます～～……んっあああっ♡": "Hức, a a aa♡ Không được rồi…… Trong đầu tại hạ…… c-cái gì đó đang tới!<br>T-Tại hạ thực sự phát điên mất thôi～～…… ưm a aa♡",
    "子宮口が降りてきて、亀頭を優しく包み込む。<br>結合がさらに深くなり、２人の一体感が増していく。": "Cửa tử cung hạ xuống dịう dàng ôm trọn lấy quy đầu.<br>Sự kết hợp càng thêm sâu sắc, cảm giác hòa làm một giữa hai người càng tăng thêm.",
    "あああっ♡　やぁ、だめ……怖い、ですっ……<br>頭の中が爆発しちゃいそう……！　ぁああ、やぁ、くる、きちゃう……！": "A aa♡ Đừng, không được…… sợ quá……<br>Trong đầu như sắp nổ tung rồi……! A aa, tới, sắp tới rồi……!",
    "ああっ、あっ、あっ、あっ……<br>あああぁぁぁぁぁぁ～～～～～～……ッ♡♡♡": "A aa, a, a, a……<br>A a a a a a a a ～～～～～～……♡♡♡",
    "しっぽも耳もビクビクと激しく痙攣させながら、コトノが絶頂に達する。<br>それと同時に、急激に収斂していく膣内に、白い滾りを吐き出していった。": "Chiếc đuôi cùng đôi tai giật run dữ dội, Kotono chạm tới đỉnh điểm.<br>Cùng lúc đó, tôi phóng thẳng dòng tinh dịch trắng nóng hổi vào trong âm đạo đang co bóp kịch liệt.",
    "んっ……んんっ……はぁっ……はぁっ……<br>うぅっ……んっ……ぅうん……": "Ưm…… hừm…… hà…… hà……<br>Ưu…… ưm…… ừm……",
    "コトノは小さな痙攣を繰り返しながら、荒い呼吸を整えている。<br>汗の珠がコトノの肌に浮かび、宝石のように光っている。": "Kotono vừa khẽ giật mình liên hồi vừa điều hòa lại hơi thở gấp gáp.<br>Những giọt mồ hôi đọng trên làn da lấp lánh như viên ngọc quý.",
    "んっ……はぁっ……はぁっ……<br>き、気持ち……よかった……": "Ưm…… hà…… hà……<br>S-Sướng…… lắm……",
    "はぁ、はぁ……んっ、あっ、あぁぁぁ……っ♡<br>すご、い……です……": "Hà, hà…… ưm, a, a aa……♡<br>T-Tuyệt quá……",
    "ひたすら蠕動を繰り返す胎内から陰茎を引きずり出すと、<br>コトノの子宮で受け止めきれなかった精液が流れ落ちてくる。": "Khi tôi rút dương vật ra khỏi khoang bụng đang liên tục co bóp,<br>dòng tinh dịch mà tử cung Kotono không chứa hết liền trào ra ngoài.",
    "はぁ……はぁ……頭の中が真っ白になって……<br>お、おかしくなるかと思いました……": "Hà…… hà…… Trong đầu trống rỗng luôn……<br>T-Tưởng như sắp điên mất rồi……",
    "体力を使い果たしたのか、しっぽと耳がへたり、ぐったりとしている。<br>だがその顔には、幸福感に満ちた表情が浮かんでいた。": "Có lẽ vì kiệt sức nên đuôi và tai rủ xuống rũ rượi.<br>Thế nhưng trên gương mặt cô ấy lại đượm vẻ hạnh phúc đong đầy.",
    "あの、旦那様は……？<br>あ、あの……私の体で満足……していただけたのでしょうか？": "Dạ, Tướng công……?<br>T-Thân thể tại hạ…… ngài có cảm感じ hài lòng không ạ?",
    "ああ。気持ちよかったよ。<br>今からもう一度したいくらいだ。": "Ừ, sướng lắm.<br>Giờ ta thậm chí còn muốn làm thêm lần nữa đây.",
    "えぇっ！？　こ、こんなにいっぱい出したというのにまだ……？<br>む、むむむ無理です！　私の体の方が壊れてしまいます！": "Ehh!? Đ-Đã ra nhiều thế này rồi mà vẫn còn nữa sao……?<br>K-Không được đâu ạ! Thân thể tại hạ hỏng mất!",
    "だが、そろそろ部屋から出ないとルディアに怪しまれるだろう。<br>服を着たらすぐに部屋を出るぞ。": "Nhưng nếu không ra khỏi phòng sớm thì Rudia sẽ nghi ngờ đấy.<br>Mặc quần áo vào rồi rời khỏi phòng thôi.",
    "え？　あ……ま、待ってください……<br>私、こ、腰に力が入らなくて……": "Hả? A…… x-xin chờ chút ạ……<br>Thắt lưng tại hạ…… c-chẳng còn chút sức lực nào nữa……",
    "コトノは情けない声を出してわたわたと悶えている。<br>普段の姿とのギャップに微笑ましく思いながら、そっと手を差し伸べた。": "Kotono thốt lên giọng điệu tội nghiệp rồi ngượng ngùng luống cuống.<br>Cảm thấy nét mâu thuẫn dễ thương so với ngày thường, tôi nhẹ nhàng đưa tay ra dắt cô ấy."
}

data_13 = {
    "ずいぶんたっぷり時間をかけてたみたいですね♡": "Xem ra hai người spent khá nhiều thời gian đấy nhỉ♡",
    "部屋を出ると、冷やかすような顔のルディアが待っていた。<br>コトノは真っ赤になってしっぽを丸めてしまう。": "Khi bước ra khỏi phòng, Rudia đang đứng đợi với nụ cười chọc ghẹo.<br>Kotono ngượng chín cả mặt, cuộn tròn chiếc đuôi lại.",
    "で、お仕事のお部屋は気に入っていただけました？": "Thế nào, căn phòng làm việc em có ưng意 không?",
    "あ……はい、もちろんです。<br>ホウライのお屋敷のようですごく落ち着けるお部屋でした。": "A…… vâng, dĩ nhiên rồi ạ.<br>Căn phòng như một dinh thự Hourai khiến em cảm thấy vô cùng thư thái.",
    "お布団はどうでした？<br>試してみたんでしょう？": "Thế còn chăn nệm thì sao?<br>Hai người đã dùng thử rồi đúng không?",
    "え！？　お布団って……ま、まさか……！<br>私と旦那様がお布団で交わってたの……の、覗いてたんですか！？": "Hả!? Chăn nệm…… n-chẳng lẽ nào……!<br>Em và Tướng công làm chuyện đó trên chăn nệm…… c-chị đã lén nhìn sao!?",
    "おい！　コトノ！": "Này! Kotono!",
    "うふふ、なんてわかりやすい反応なんでしょう♡<br>かまをかけただけなのに、素直な子ですね～。": "Ứ hừ, đúng là phản ứng dễ đoán làm sao♡<br>Chị mới gài bẫy có chút thôi mà em thật thà quá đi mất～",
    "ルディアのトラップに簡単に引っかかってしまうコトノに<br>たまらず頭を抱えてしまう。": "Thấy Kotono dễ dàng sập bẫy của Rudia,<br>tôi không khỏi ôm đầu bất lực.",
    "え！？　え！？　ひょっとして……<br>わ、私が自分で白状しちゃったってこと！？": "Hả!? Hả!? Chẳng lẽ……<br>T-Tự em đã khai ra hết rồi sao!?",
    "司令官君、コトノさんの最初のお客様になってあげたんでしょう？<br>それなら、ちゃんとお代を払ってあげてね♪": "Tư lệnh à, cậu đã trở thành vị khách đầu tiên của Kotono đúng không?<br>Nếu vậy thì phải trả tiền đàng hoàng cho em ấy đấy nhé♪",
    "最初のお客！？　そういうことになるのか？": "Vị khách đầu tiên!? Tính ra là như thế sao?",
    "寝室でウチの女の子と楽しんだんですもの。<br>その分のお代はしっかりといただかないとね♡": "Dù sao cậu cũng đã vui vẻ với cô gái nhà chị trong phòng ngủ rồi mà.<br>Khoản tiền đó dĩ nhiên phải thu đầy đủ rồi♡",
    "まぁ、布団も汚してしまったからな。<br>もちろん支払うよ。": "Mà, dù sao cũng làm bẩn chăn nệm rồi.<br>Đương nhiên là ta sẽ trả tiền thôi.",
    "よかったわね、初めてのお給料。<br>これからもよろしくね、コトノさん♡": "Tốt quá rồi nhé, tiền lương đầu tiên đấy.<br>Từ nay về sau cũng nhờ em nhiều nhé, Kotono♡",
    "あ……はい！　何事も鍛錬あるのみです！<br>不撓不屈の精神で頑張ります！": "A…… vâng! Mọi việc đều là rèn luyện!<br>Em sẽ nỗ力 với tinh thần bất khuất không lùi bước!",
    "コトノはすっかりやる気になり、いつもの笑顔を見せるのだった。": "Kotono tràn đầy khí thế trở lại, nở nụ cười rạng rỡ thường ngày."
}

data_21 = {
    "コトノが娼館で働き始めて一か月が経とうとしたある日のこと――": "Một ngày nọ, khoảng một tháng sau khi Kotono bắt đầu làm việc tại kỹ viện——",
    "なるほど。武者修行の為にこの前線基地にいらっしゃったと、<br>自己鍛錬に勤しむ心掛けは素晴らしいと思いますね。": "Ra là thế. Nghe nói ngài đến căn cứ tiền tuyến này để tu luyện võ nghệ,<br>tinh thần siêng năng tự rèn luyện ấy quả thật rất đáng khâm phục.",
    "この日のコトノの指名客は武者修行の為に前線基地にやって来た若者で<br>ホウライでも屈指の女剣豪というコトノの噂を聞いて会いに来たのだと言う。": "Vị khách chỉ định Kotono hôm nay là một thanh niên tới căn cứ tiền tuyến để tu luyện võ nghệ.<br>Cậu ta nói vì nghe đồn Kotono là nữ kiếm hào kiệt xuất tại Hourai nên mới tới tìm gặp.",
    "（武者修行っていうけれど、本当に武芸者なのか疑わしいな……<br>体つきも華奢だし、本当に鍛錬しているのか否か……）": "(Gọi là tu luyện võ nghệ nhưng không biết có đúng là võ giả không nữa……<br>Thân hình mảnh khảnh thế này, liệu có thực sự rèn luyện không đây……)",
    "私と手合わせしたいのでしたら、是非、訓練所に顔を出してください。<br>師範代として働いていますので、いつでもお相手いたしましょう。": "Nếu ngài muốn giao đấu với tại hạ thì xin mời ghé qua huấn luyện sở.<br>Tại hạ làm trợ giảng ở đó nên lúc nào cũng sẵn sàng nghênh đón.",
    "コトノと手合わせと言いながら娼館にやってきた客にコトノは呆れ顔だ。<br>だが若者は、剣術ではとても敵わないからと真顔で答える。": "Kotono tỏ ra ngán ngẩm trước vị khách bảo muốn giao đấu nhưng lại tìm đến kỹ viện.<br>Thế nhưng gã thanh niên lại đáp với vẻ mặt nghiêm túc rằng vì về kiếm thuật gã hoàn toàn không phải đối thủ của cô.",
    "（ん～……何を考えているのかよく分からない若者だけど……<br>手早く御奉仕して、さっさとお帰り願いましょうかねぇ）": "(Ưm…… Đúng là gã thanh niên khó hiểu……<br>Chi bằng phục vụ nhanh chóng rồi mời gã về sớm cho xong)",
    "このままお話を続けても時間が勿体ないですよ。<br>そろそろ床の間に参りましょう。": "Tiếp tục nói chuyện thế này thì phí thời gian lắm.<br>Chúng ta mau vào giường thôi.",
    "コトノは若者の手を取り、布団へと誘う。<br>その腕は、やはり武芸者にしては細すぎるとコトノは思った。": "Kotono nắm lấy tay gã thanh niên, dẫn gã về phía chăn nệm.<br>Cô nghĩ thầm cánh tay này quả nhiên quá mảnh khảnh so với một võ giả.",
    "えぇ……っ！？": "Ehh……!?",
    "不意にコトノの脚に、男の脚が絡みつき、<br>コトノの視界が反転する。": "Bất ngờ chân gã nam nhân ngáng chặt lấy chân Kotono,<br>khiến tầm mắt Kotono đảo ngược.",
    "な……何を！？　くうっ！": "C-Cái gì!? Hự!",
    "若者が不意打ちで足を絡め、投げ技を放ったのであった。<br>コトノはとっさに受け身を取ったが、すぐに若者が抑え込みにかかる。": "Gã thanh niên đánh lén ngáng chân rồi tung đòn quật ngã.<br>Kotono lập tức thực hiện tư thế giảm chấn nhưng đã bị gã nhanh chóng khống chế chèn đè lên."
}

data_22 = {
    "くっ……！　不意打ちとは卑怯じゃないですか！": "Hự……! Đánh lén thật là đê hèn!",
    "気づけばコトノは、布団の上であられもない姿にされていた。<br>若者が背後からコトノに絡み付いている。": "Khi nhận ra thì Kotono đã bị đè xuống chăn nệm trong một tư thế vô cùng ngượng ngùng.<br>Gã thanh niên ôm chặt lấy cô từ phía sau.",
    "抗議しながら起き上がろうとするが、体が思うように動かない。": "Vừa phản đối cô vừa cố ngồi dậy, nhưng cơ thể lại không thể cử động theo ý muốn.",
    "（み、身動きが取れない……？　これは……）": "(Kh-Không thể nhúc nhích được……? Đây là……)",
    "さてはあなた、柔術使いでしたか。<br>なるほど、ここで手合わせしようと、そういう魂胆でしたか……": "Hóa ra ngài là người luyện Nhu thuật sao.<br>Ra là vậy, ngài đến đây là có mưu đồ muốn giao đấu bằng cách này……",
    "背後で若者がフッと微笑む気配。<br>華奢な若者と侮っていたが、見事にコトノの関節を極め身動きを封じていた。": "Từ phía sau có cảm giác gã thanh niên khẽ mỉm cười.<br>Dù từng coi thường gã là mảnh khảnh nhưng gã đã khóa chặt các khớp xương của Kotono khiến cô hoàn toàn bất động.",
    "そうと分かれば容赦はしませんよ。<br>私だって、柔術の心得くらいは……": "Đã biết vậy rồi thì tại hạ sẽ không nương tay đâu.<br>Tại hạ đây cũng hiểu biết chút ít về Nhu thuật……",
    "……え？": "……Hả?",
    "だが、コトノはすぐに身を硬くした。<br>股間に違和感を感じたのだ。": "Thế nhưng Kotono lập tức cứng đơ người.<br>Cô cảm nhận được sự kỳ lạ nơi vùng háng.",
    "熱くて硬い焼けた鉄の棒のような感触。<br>視線を下げて確かめると、それは男の屹立した陰茎だった。": "Cảm giác nóng rực và cứng đờ như một thanh sắt nung.<br>Hạ tầm mắt nhìn xuống xác nhận, đó chính là dương vật đang chào cờ cương cứng của gã nam nhân.",
    "（な……！？　お、大きい……？）": "(C-Cái gì……!? T-To quá……?)",
    "華奢な男の体躯からは想像つかないくらい、それは巨大な肉棒だった。<br>それを見た途端、金縛りに遭ったように体が動かなくなってしまう。": "Đó là một thanh thịt khổng lồ đến mức không thể tưởng tượng nổi từ vóc dáng mảnh khảnh của gã nam nhân.<br>Vừa nhìn thấy nó, cơ thể cô lập tức như bị bất動 không thể nhúc nhích.",
    "（すごい……あんなに先端が大きく張りつめている……赤児の拳のような……<br>あんなモノを私の中に挿れられたら……）": "(Ghê quá…… Đầu nó căng tròn to đùng đến thế kia…… như nắm đấm em bé vậy……<br>Thứ như vậy mà đâm vào trong người mình thì……)",
    "想像すると体が震えた。<br>恐怖なのか歓びなのかは自分でもわからない。": "Chỉ mới tưởng tượng thôi mà cơ thể cô đã run lên.<br>Chính cô cũng chẳng rõ đó là nỗi sợ hãi hay sự sung sướng nữa.",
    "コトノはもう抵抗も忘れて男のモノに目と心を奪われている。<br>すると男は、その凶暴な先端をコトノの中心にあてがってきた。": "Kotono đã quên mất việc chống cự, mắt và tâm trí hoàn toàn bị thu hút bởi của gã nam nhân.<br>Ngay sau đó, gã kề cái đầu hung tợn của nó vào ngay trung tâm của Kotono.",
    "（し、しまった！　私としたことが……！）": "(Th-Thôi chết rồi! Tại hạ thật là……!)",
    "んぐぅ……っ！？　あっ！　ぁあああぁぁぁぁ～～～～ッ！": "Hức……!? A! A a a a ～～～～!",
    "戸惑っているコトノの秘処に、男は強引に侵入してきた。<br>まだ十分に濡れていないそこは、男の巨大な先端だけで悲鳴を上げている。": "Gã男 nhân thúc mạnh vào chỗ thầm kín của Kotono trong lúc cô còn bàng hoàng.<br>Nơi chưa kịp ướt đẫm ấy đã thốt lên tiếng thét chỉ vì cái đầu khổng lồ của gã.",
    "ぐっ……はぁっ、はぁっ、はぁっ……<br>くぅっ……まだ準備もできてないのに……": "Hự…… hà, hà, hà……<br>Hự…… tại hạ còn chưa chuẩn bị xong mà……",
    "容赦なく捻じ込まれた男根が、コトノの膣内でドクドクと鼓動している。<br>興奮した男の荒い鼻息が、首筋をくすぐる。": "Cái nương căn bị nhồi nhét không chút nương tay đang đập thình thịch trong âm đạo Kotono.<br>Hơi thở dồn dập hưng phấn của gã nam nhân mơn trớn trên gáy cô.",
    "（あぁ……す、すごく大きい……<br>私の中で、脈打ってるのが分かる……）": "(Aa…… r-rất to lớn……<br>Mình cảm nhận được nó đang giật từng nhịp bên trong cơ thể……)",
    "その時、コトノの子宮奥からドプドプと愛蜜が溢れてくる。<br>強引に挿入された男の肉棒を、身体が受け入れようとしているのだ。": "Đúng lúc đó, dâm mật ồ ạt trào ra từ sâu trong tử cung Kotono.<br>Cơ thể cô đang tự động mở ra đón nhận thanh thịt vừa bị cưỡng ép đâm vào.",
    "（やだ……身体が、勝手に求めちゃってる……！？<br>どんどん熱くなって……勝手に濡れてきてる……）": "(Đừng mà…… Cơ thể mình lại tự động thèm muốn nó sao……!?<br>Ngày càng nóng lên…… và tự dưng ướt đẫm ra thế này……)",
    "それに気づいた若者が、下卑た笑い声を漏らした。<br>コトノは屈辱と羞恥を感じたが、逆に体の奥がさらに火照ってしまう。": "Nhận ra điều đó, gã thanh niên bật ra tiếng cười bỉ ổi.<br>Kotono cảm thấy nhục nhã và xấu hổ, nhưng sâu trong cơ thể lại càng thêm nóng rạo rực.",
    "（や、やだ……もっと欲しくて、たまらない……<br>私、いつの間にこんなに淫らな身体になってしまったんだろう……？）": "(Đ-Đừng mà…… Thèm muốn nhiều hơn nữa, không chịu nổi mất rồi……<br>Tự bao giờ cơ thể mình lại trở nên dâm đãng đến thế này chứ……?)",
    "ああああっ！？　ちょ、ちょっと……んんっ！<br>きゅ……急に……！　あっ……あぁっ……やあぁぁっ！": "A aa!? Ch-Chờ chút…… hừm!<br>Đ-Đột ngột……! A…… aa…… ya a!",
    "コトノの膣内が準備を整えたことを読み取ったように、<br>若者は抽送を開始したのである。": "Như đọc được âm道 Kotono đã sẵn sàng, <br>gã thanh niên bắt đầu thực hiện nhịp nhấp dâm dật.",
    "ま、待って！　ま、まだそこまで準備が……<br>もうちょっと、ゆ、ゆっくり……くぅぅっ……ぁはぁっ！": "Ch-Chờ đã! T-Tại hạ chưa chuẩn bị tới mức đó đâu……<br>Chậm…… chậm lại chút…… hự…… a hà!",
    "言葉とは裏腹に、コトノの膣内はまたみるみる潤っていく。<br>結合部からいやらしい水音が絶え間なく聞こえてきた。": "Trái ngược với lời nói, bên trong âm đạo Kotono lại ướt đẫm ra nhanh chóng.<br>Nơi giao hợp vang lên tiếng nước dâm dật không ngừng.",
    "ぅうんっ、んっ、んくっ……す、すごく、大きいのが……私の中で……！<br>やぁっ！　あっ……ダメぇっ！　んんっ……はぁあっ……んんっ、ううん……": "Ừm, ưm, hức…… thứ r-rất to lớn…… đang ở trong người tại hạ……!<br>Đừng mà! A…… không được! Hừm…… hà a…… hừm, ừm……",
    "んっ、はぁぁっ……ぁああぁっ……！　こ、こんなの……やぁっ……！<br>あっ……あっ……ぁあんっ！　あっ……ぁあんっ、あんっ、ぁああぁっ♡": "Ưm, hà aa…… a aa……! Th-Thứ này…… đừng mà……!<br>A…… a…… a ưm! A…… a ưm, a ưm, a aa♡",
    "コトノの声はどんどん甘く、そして大きくなっていった。<br>最初は必死に声をこらえようとしていたが、既に抑えきれなくなっている。": "Tiếng rên của Kotono ngày càng ngọt ngào và to hơn.<br>Ban đầu cô cố hết sức nín kìm tiếng rên nhưng giờ đã hoàn toàn không thể kiềm chế nổi nữa.",
    "（もう駄目……このままじゃすぐ、イカされちゃう……<br>あぁ……旦那様……）": "(Không được rồi…… Cứ thế này mình sẽ bị làm cho lên đỉnh mất thôi……<br>Aa…… Tướng công ơi……)",
    "だがその時、ぬぷっといういやらしい音とともに、<br>コトノの膣内から陰茎の感触が消えた。": "Nhưng ngay lúc đó, cùng với tiếng 'phút' dâm dật,<br>cảm giác dương vật bên trong âm đạo Kotono chợt biến mất.",
    "え……ひうっ……！？": "Hả…… hơ u……!?",
    "驚いて股間を見下ろすと、男の肉棒が抜けている。": "Giật mình nhìn xuống háng, thanh thịt gã nam nhân đã rút ra ngoài.",
    "なっ……ど、どうして……？<br>あと少しでイきそうだったのに……": "Cái…… s-sao lại thế……?<br>Chỉ chút nữa thôi là tại hạ lên đỉnh rồi mà……",
    "振り返って確認しようとするが、若者はニヤニヤするばかりで動こうとしない。": "Cô quay lại muốn xác nhận nhưng gã thanh niên chỉ nhe răng cười bỉ ổi chứ không chịu cử động.",
    "な、何を焦らしてるんですか……！？<br>お、お願い……さっきの続きを……は、早く……！": "N-Ngài đang cố tình trêu ngươi tại hạ đấy à……!?<br>X-Xin ngài…… tiếp tục khi nãy đi…… m-mau lên……!",
    "振り返って訴えるが、若者は下卑た笑みを浮かべるばかりだ。<br>焦れているコトノの反応を楽しむようにただじっとしている。": "Quay lại cầu xin nhưng gã thanh niên vẫn chỉ giữ nụ cười hạ lưu.<br>Gã chỉ đứng yên hưởng thụ phản ứng cuống cuồng của Kotono.",
    "（や、ヤダ……私としたことが、なんてはしたないことを言ってるの……<br>駄目だ……男女の交わりに関しては完全にこの若者の方が上手……）": "(Đ-Đừng mà…… Bản thân mình lại nói ra những lời hư hỏng thiếu liêm xỉ thế này sao……<br>Không xong rồi…… Về chuyện áい ân nam nữ thì gã thanh niên này hoàn toàn cao tay hơn hẳn rồi……)",
    "コトノさんがこんなに敏感な身体だとは意外でした。<br>こっちの穴もヒクヒクしてますよ。": "Tôi chẳng ngờ cơ thể Kotono tiểu thư lại nhạy cảm đến thế đấy.<br>Cái lỗ bên này cũng đang giật giật thèm muốn kìa.",
    "え？　こっちの穴って……": "Hả? Lỗ bên này là……",
    "コトノが戸惑っていると、若者はコトノの後ろの穴に亀頭先を擦りつけてくる。": "Trong lúc Kotono còn ngơ ngác, gã thanh niên kề đầu quy頭 cạ vào cái lỗ sau của Kotono.",
    "ひっ！　ちょ、ちょっと……そんな変なところに当てないでっ！<br>んんっ…んっ……ぁあっ♡": "Hí! Ch-Chờ chút…… đừng chạm vào chỗ kỳ quái đó chứ!<br>Hừm… ưm…… a aa♡",
    "アナルへの愛撫に敏感に反応しながら、<br>コトノはこの若者のある企みに気が付いてしまう。": "Trong lúc nhạy cảm phản ứng với sự vuốt ve nơi hậu môn,<br>Kotono chợt nhận ra ý đồ mưu mẹo của gã thanh niên này.",
    "えっ……まさか……！？　ま、待って！　な、何を考えて……？<br>そ、そっちは……ち、違う穴だぞ！": "Hả…… chẳng lẽ nào……!? Ch-Chờ đã! N-Ngài tính làm gì thế……?<br>Đ-Đó là…… l-lỗ khác mà!",
    "ひぐっ！　えっ！？　ウソ、ま、待って待っ……あううっ！<br>んぐっ……ンググググッ！　ぁあああぁっ！！": "Hức! Hả!? Không thể nào, ch-chờ đã…… a uuu!<br>Hức…… hừm hừm hừm! A a aa!!",
    "男の肉棒は、コトノの愛蜜でヌルヌルの状態だった。<br>それが潤滑油となって、ギュッと閉じていた菊門に容易に侵入を許してしまう。": "Thanh thịt của gã nam nhân đã trơn trượt bởi dâm mật của Kotono.<br>Chính nó trở thành chất bôi trơn giúp nó dễ dàng xâm nhập vào cúc môn đang đóng chặt.",
    "えっ……えぇっ！？　あぁ、ウソ……本当に入ってしまった！？<br>う、ウソでしょ！？　こ、こんなの……": "Hả…… Ehh!? Aa, dối lừa…… thực sự vào trong rồi sao!?<br>Đ-Đùa đúng không!? Ch-Chuyện này……",
    "直腸壁に沈み込んだ肉棒を感じ、コトノは身体を強張らせる。<br>呼吸も苦し気で、時々喉を鳴らしている。": "Cảm nhận được thanh thịt ngập sâu vào thành trực tràng, Kotono gồng cứng cơ thể.<br>Hơi thở cô nghẹn ngào, thỉnh thoảng nấc lên trong họng.",
    "んんっ、こ、こんなの……本当に……だ、大丈夫なの……！？": "Hừm, th-thế này…… thực sự…… c-có ổn không vậy……!?",
    "コトノは未知の体験に畏怖し、すっかり硬直してしまっている。<br>体を串刺しにされたような気分だった。": "Kotono khiêu sợ trước trải nghiệm chưa từng có, hoàn toàn đơ cứng.<br>Cô cảm thấy như cơ thể mình vừa bị xiên ngang.",
    "ひぐうっ！？　や、あぁ……ダメです、動かしちゃ……<br>んぐ、んっ、ンググ……うううっ！": "Hức uuu!? Đừng, aa…… Không được nhúc nhích đâu……<br>Hức, ưm, hừm hừm…… uuu!",
    "（な……何、これ……！？　こ、こんなの初めて……！<br>中でおちんちんが動くたび、バチバチと火花が飛ぶみたいな……）": "(C-Cái gì thế này……!? L-Lần đầu tiên mình thấy thế này……!<br>Mỗi lần bộ phận sinh dục nhúc nhích bên trong là như có tia lửa nổ bách bách bay tung tóe……)",
    "ひぐっ！　んんんっ……んっく、んはぁっ……！<br>あっ、ああっ、あっ、ああぁぁぁ……♡": "Hức! Hừm…… hức, hà……!<br>A, a aa, a, a a aa……♡",
    "（苦しい、のに……それだけじゃない……凄く……気持ちいい……？）": "(Dù đau đớn…… nhưng không chỉ vậy…… r-rất…… sướng sao……?)",
    "やん、あぁぁ……っ♡　こ、こんなの、変……<br>変なのに……ひゃうっ、あぁ……感じちゃう……気持ち……いい♡": "Đừng mà, a aa……♡ Th-Thế này thật kỳ quặc……<br>Kỳ quặc thế mà…… hơ u, aa…… lại thấy có cảm giác…… sướng…… quá♡",
    "腰を動かされる度、苦痛と快感が交互にコトノを襲う。<br>苦痛だけなら苦しいだけだが、すぐにそれを上回る快感がやってくる。": "Mỗi lần gã nhấp hông, đau đớn và khoái cảm lại luân phiên tấn công Kotono.<br>Nếu chỉ có đau đớn thì là đau đớn, nhưng ngay lập tức khoái cảm áp đảo lại ập tới.",
    "あんっ、んぐっ……んんんんっ……くぅっ……！<br>はぁっ……あぁぁあぁっ……ひぁっ♡　あぁぁぁっ♡": "A ưm, hức…… hừm hừm…… hự……!<br>Hà…… a a aa…… hơ♡ A aa♡",
    "腸奥深くに肉棒が刺さる時の膨張感による苦しさと、<br>腸壁を引っ掛けながら後退する時の快感が、交互に襲う。": "Cảm giác đau đớn do sự căng phồng khi thanh thịt cắm sâu vào ruột,<br>và khoái cảm khi nó miết vào thành ruột rút ra luân phiên dâng trào.",
    "ふぁぁぁぁっ！？　な、なに、これ……♡<br>や、あぁ、ああああっ！　すごい、気持ちいい♡": "Phơ a aaa!? C-Cái gì thế này……♡<br>Đừng, aa, a aaa! Tuyệt quá, sướng quá♡",
    "苦痛と快感のギャップの連続に、コトノは戸惑いながらも<br>若者の抽送に身を委ねる。": "Trong sự liên tiếp trái ngược giữa đau đớn và khoái cảm, Kotono dù bàng hoàng<br>vẫn phó mặc cơ thể cho nhịp nhấp dâm dật của gã thanh niên.",
    "ひぐっ、んっぐうううっ♡<br>何これ！？　あ、頭の中……へ、変になりそう……！": "Hức, hức uuu♡<br>Cái gì thế này!? Đ-Đầu óc mình…… s-sắp phát điên rồi……!",
    "んぐっ……く、苦しいのに……ああぁっ♡　す、すぐに気持ちよくなって……<br>はぁっ……はぁっ……んんっ！　はぁ……あっ、あっ、気持ちいぃ……っ♡": "Hức…… D-Dù đau đớn…… a aa♡ N-Nhưng ngay lập tức lại sướng……<br>Hà…… hà…… hừm! Hà…… a, a, sướng quá……!",
    "ぁああぁっ……♡　も、もう……だめぇっ……気持ちよすぎて……<br>イ……イクっ！　はぁ……あっ、イッちゃうぅぅぅうぅ～～～～っ！": "A a aa……♡ K-Không…… được rồi…… sướng quá mất thôi……<br>L-Lên đỉnh đây! Hà…… a, lên đỉnh mất rồi ～～～～!",
    "コトノが絶頂を向かえると同時に、<br>コトノの腸奥で、若者の熱い精液を吐き出される。": "Cùng lúc Kotono chạm tới đỉnh điểm,<br>sâu trong ruột cô, gã thanh niên cũng bắn ra dòng tinh dịch nóng hổi.",
    "はぁっ……はぁっ……も、もう……ダメ……<br>気持ちよすぎて……頭が変になりそうだった……": "Hà…… hà…… K-Không…… được nữa rồi……<br>Sướng quá…… đầu óc tưởng như sắp phát điên……",
    "な、何なの……？　こ、こんなの繰り返されたら……<br>私、死なないまでも、狂ってしまうかもしれない……": "C-Cái gì thế này……? N-Nếu cứ lặp lại thế này thì……<br>Dù không chết thì chắc mình cũng điên mất thôi……",
    "絶頂に達した肛門が、強烈に収縮を繰り返す。<br>その直腸の動きが、若者から精子を搾り取っていく。": "Hậu môn vừa lên đỉnh co bóp mãnh liệt liên hồi.<br>Cử động của trực tràng vắt cạn từng giọt tinh trùng từ gã thanh niên.",
    "あぁぁ……んぐ……はぁぁぁ……はぁっ……はぁっ……<br>お尻の中……凄く熱い……": "Aa…… hức…… hà aa…… hà…… hà……<br>Bên trong mông…… nóng quá……",
    "しっぽと耳を垂れ、コトノは息も絶え絶えに横たわっている。": "Đuôi và tai rủ xuống, Kotono nằm thoi thóp thở.",
    "若者もさすがに疲弊した様子だ。<br>射精して少し冷静になったのか、突然の乱暴な振る舞いをコトノに詫びてくる。": "Gã thanh niên xem ra cũng đã mệt mỏi kiệt sức.<br>Có lẽ sau khi bắn tinh gã đã tỉnh táo lại đôi chút nên lên tiếng xin lỗi Kotono vì hành vi thô bạo đột ngột.",
    "いえ……”先の先”……というやつ、ですね……<br>常に相手の先手を取る、見事な仕掛けでした……": "Không……”Tiên chi tiên”…… chính là nó đấy nhỉ……<br>Luôn chiếm thế chủ động trước đối phương, quả là một mưu đòn tuyệt vời……",
    "手も足も出ずに、やられてしまいましたね……<br>今日のところは完敗です……": "Tại hạ hoàn toàn không thể chống đỡ và bị khuất phục rồi……<br>Hôm nay coi như tại hạ hoàn toàn đại bại……"
}

data_23 = {
    "息も絶え絶えに横たわりながら、コトノは負けを認めた。": "Vừa nằm thoi thóp thở, Kotono vừa thừa nhận thất bại của mình.",
    "着衣の乱れを直したコトノは、ようやく冷静さを取り戻し、<br>いつものホウライの剣士としての威厳を取り戻していた。": "Chỉnh đốn lại trang phục xộc xệch, Kotono cuối cùng đã lấy lại sự bình tĩnh,<br>khôi phục lại uy nghiêm vốn có của một kiếm sĩ Hourai.",
    "それだけ腕が立つんですから、武者修行の必要なんてないのでは？": "Ngài có thân thủ cao cường thế này thì đâu cần phải đi tu luyện võ nghệ nữa chứ?",
    "だが若者はすっかり謙虚になり、柔術の心得はあるものの、<br>腕力がないために、剣術など武器の扱いには不慣れなことを告げる。": "Thế nhưng gã thanh niên đã hoàn toàn khiêm tốn lại. Gã thú nhận tuy có hiểu biết Nhu thuật,<br>nhưng vì lực tay yếu nên không quen dùng vũ khí như kiếm術.",
    "剣の腕を磨きたければいつでも訓練所に来てください。<br>剣術も腕力ではなく、肩の力を抜いて身体全体で剣を振るうのがコツですよ。": "Nếu muốn rèn luyện kiếm thuật thì ngài cứ ghé qua huấn luyện sở bất cứ lúc nào.<br>Bí quyết của kiếm thuật cũng không nằm ở lực tay, mà là thả lỏng vai và dùng toàn thân để múa kiếm.",
    "この辺りは座学で学べるものではないですから是非訓練所にいらしてください。<br>柔術では完敗しましたけど、剣術ではビシバシと鍛えて差し上げますから。": "Những thứ này không thể học trên sách vở được nên nhất định ngài hãy đến huấn luyện sở nhé.<br>Về Nhu thuật thì tại hạ hoàn toàn đại bại, nhưng về kiếm thuật thì tại hạ sẽ huấn luyện ngài ra trò đấy.",
    "だが若者はとんでもないと、困ったように頭を掻いている。<br>さっき、いつでも抜け出せたはずなのに、手を抜いていたじゃないですか、と。": "Thế nhưng gã thanh niên ngượng ngùng gãi đầu bảo không dám.<br>Gã bảo khi nãy rõ ràng cô có thể thoát ra bất cứ lúc nào nhưng lại cố tình nương tay đúng không.",
    "え、ええっ……！？　まさか、見抜かれているとは……<br>ええと……確かに途中からいつでも抜け出せる状態だったのは事実です。": "Hả, Ehh……!? Không ngờ lại bị ngài nhìn thấu……<br>Ừm…… Đúng là nửa chừng tại hạ đã ở trong trạng thái có thể thoát ra bất cứ lúc nào.",
    "ですが、あまりの気持ちよさについ……<br>わざと続けさせてしまいました……": "Thế nhưng vì quá sướng nên tại hạ lỡ……<br>cố tình để ngài tiếp tục……",
    "快感に身を任せてしまった事実を語り、恥ずかしそうにコトノは頭を掻く。": "Nói ra sự thật rằng mình đã phó mặc cho khoái cảm, Kotono ngượng ngùng gãi đầu.",
    "若者は、やはりコトノさんには敵いませんと、深々とお辞儀をすると<br>娼館を後にしていった。": "Gã thanh niên cúい đầu thật sâu bảo quả nhiên gã vẫn không thể thắng được Kotono tiểu thư,<br>rồi rời khỏi kỹ viện."
}

data_31 = {
    "はぁ、はぁ……あんっ、んっ、あぁぁ……だ、旦那……様……<br>んっ、んっ、ぁあっ……あはぁっ……ぅうんっ、はあぁっ、あっ……": "Hà, hà…… a ưm, ưm, a aa…… T-Tướng…… công……<br>Ưm, ưm, a a…… a hà…… ừm, hà a, a……",
    "あああっ♡　はんっ、あぁ、旦那様……あぁっ、んんっ、いいっ……<br>んっく……イ……イクっ……ぅうんっ、あぁぁぁぁ……♡": "A aa♡ Hả ưm, aa, Tướng công…… aa, hừm, sướng quá……<br>Hức…… L-Lên đỉnh đây…… ừm, a a a a……♡",
    "んんんっ……イっちゃうぅぅぅぅぅぅぅぅ～～～～～～～～～～～～………♡": "Hừm…… Lên đỉnh mất rồi ～～～～～～～～～～～～……♡",
    "はぁ、んっ……はぁ、はぁ、はぁ……": "Hà, ưm…… hà, hà, hà……",
    "コトノは上気したまま、呼吸を乱している。<br>その全身から吹き出る汗は、甘く淫靡な香りを発散していた。": "Kotono mặt đỏ bừng gắt gỏng, hơi thở dồn dập loạn nhịp.<br>Mồ hôi vỡ ra khắp thân thể cô tỏa ra một mùi hương ngọt ngào và dâm dật.",
    "ダメだ、全然収まらない……このままじゃ……<br>早く、旦那様に相談しないと。": "Không được rồi, hoàn toàn không lắng xuống…… Cứ thế này thì……<br>Phải nhanh chóng bàn với Tướng công mới được.",
    "コトノ……？　そこに居るのか……？<br>急にどうしたんだよ、こんな夜更けに。": "Kotono……? Cậu ở đó đấy à……?<br>Sao đột nhiên đêm hôm thế này lại gọi ta.",
    "あ、旦那様。<br>も、申し訳ございません。こんなお時間に呼び出してしまい……": "A, Tướng công.<br>R-Rất xin lỗi ngài vì đêm hôm thế này lại gọi ngài ra……",
    "いや、気にすることはない。<br>しかし、こんな人気のないところで相談とは何か厄介なことなのか？": "Không sao, đừng bận tâm.<br>Nhưng hẹn gặp ở nơi vắng người thế này là có chuyện gì phiền phức sao?",
    "いえ、あの、実はその……<br>な、なんと説明したらよいか……": "Dạ không, chuyện là, thực ra……<br>N-Nói thế nào cho phải đây ạ……",
    "ん？　言いづらいことなのか？<br>遠慮なく言ってくれ。": "Hả? Chuyện khó nói sao?<br>Cứ tự nhiên nói ra đi.",
    "私……来てしまったようなんです……<br>その……発情期が……": "Tại hạ…… hình như đã đến lúc rồi ạ……<br>C-Chuyện là…… mùa phát dục……",
    "発情期……！？": "Mùa phát dục……!?",
    "相談とはなにかと思ったが、発情期のことだったとは。": "Ta cứ tưởng chuyện gì, hóa ra lại là mùa phát dục.",
    "なるほどな。コトノは獣人だし、発情期があっても何もおかしくはないだろう。<br>そんなに思いつめることはないんじゃないか？": "Ra là thế. Kotono là thú nhân nên có mùa phát dục cũng đâu có gì lạ.<br>Cậu đâu cần phải trăn trở nghĩ ngợi nhiều thế chứ?",
    "ですが、ここ数日は四六時中、頭の中が淫らな妄想でいっぱいで……<br>身体の火照りも収まらなくてソワソワしてしまっているんです。": "Nhưng mấy ngày nay lúc nào trong đầu tại hạ cũng ngập tràn ảo tưởng dâm dật……<br>Cơ thể cứ nóng rạo rực không chịu lắng xuống làm tại hạ đứng ngồi không yên.",
    "毎晩自分で慰めても、全くおさまらなくて……<br>今も旦那様の姿を目にしただけで、股の間がもう……ウズウズと……": "Mỗi đêm tự mình giải tỏa cũng không thể bớt chút nào……<br>Bây giờ chỉ cần nhìn thấy bóng dáng Tướng công thôi là vùng háng tại hạ đã…… ngứa ngáy rần rật rồi……",
    "コトノは耳をシュンと倒して両太股をこすり合わせている。<br>そこが疼いて仕方ないのだ。": "Kotono ủ rũ rủ tai xuống, hai đùi cọ xát vào nhau.<br>Chỗ đó của cô ấy đang nhói lên không sao chịu nổi.",
    "このままじゃさすがに訓練所の師範代の仕事にも支障が……<br>そこで旦那様にお願いがございます……！": "Cứ thế này thì công việc trợ giảng ở huấn luyện sở cũng bị ảnh hưởng mất……<br>Thế nên tại hạ có một thỉnh cầu muốn nhờ Tướng công……!",
    "わ、私のお相手をしていただけないでしょうか！<br>不躾なお願いだとは重々承知の上でのお願いでございます！　ど、どうか……！": "L-Liệu ngài có thể giúp tại hạ giải tỏa được không ạ!<br>Tại hạ biết rõ đây là lời thỉnh cầu khiếm nhã! N-Nhưng xin ngài……!",
    "コトノの切迫した表情から、真剣に悩んでいることが伺える。<br>彼女の願いを聞き入れ、用意してあるという場所へ付いて行くことにした。": "Từ vẻ mặt cấp bách của Kotono có thể thấy cô ấy thực sự đang trăn trở lo âu nghiêm túc.<br>Chấp nhận thỉnh cầu của cô, tôi quyết định đi theo cô đến nơi cô đã chuẩn bị sẵn.",
    "そこは、コトノが師範代を務める、前線基地の訓練所だった――": "Nơi đó chính là huấn luyện sở tại căn cứ tiền tuyến mà Kotono đang làm trợ giảng——"
}

data_32 = {
    "心配には及びません。この時間なら、訓練所には誰も居りませぬ。<br>なので、ここならば誰にも気づかれることはありません。": "Không cần lo lắng đâu ạ. Giờ này trong huấn luyện sở không có ai cả.<br>Nên ở đây tuyệt đối sẽ không bị ai phát hiện đâu.",
    "訓練所の窓から注ぐ月明りが、コトノの身体を妖艶に映し出す。<br>発情期とは聞いていたが、コトノの全身から甘い色香が漂っていた。": "Ánh trăng rọi qua cửa sổ huấn luyện sở soi rọi thân thể Kotono đầy quyến rũ.<br>Dù đã nghe bảo cô ấy đang trong mùa phát dục, nhưng khắp người Kotono đều tỏa ra một mùi hương ngọt ngào dâm dật.",
    "さ、さぁ……だ、旦那様……<br>は、早く……じ、焦らさないでください……": "M-Mời ngài…… T-Tướng công……<br>M-Mau lên…… đ-đừng trêu ngươi tại hạ nữa……",
    "前かがみで柱にもたれかかり、早く挿れてくれとばかりにしっぽを立てている。<br>その内股は、秘処から垂れた体液で濡れていた。": "Cô ấy chồm người tựa vào cột nhà, dựng đuôi lên như giục giã mau đâm vào đi.<br>Phía trong đùi đã ướt đẫm bởi dâm dịch chảy ra từ chỗ thầm kín.",
    "はぁうぅっ……んっ♡　ふうぅぅぅぅ～～～……": "Hà uuu…… ưm♡ Phù uuuu～～～……",
    "コトノの尻肉の間を亀頭でなぞってやっただけで、<br>妙に敏感な反応を示す。": "Chỉ mới lấy quy đầu quệt qua khe mông Kotono thôi,<br>cô ấy đã tỏ ra phản ứng nhạy cảm một cách lạ thường.",
    "（や、ヤダ……お尻にちょっと擦られただけで、変な声が……）": "(Đ-Đừng mà…… Chỉ mới cạ mông một chút thôi mà đã phát ra tiếng kỳ quái rồi……)",
    "もう辛抱できないといったコトノの反応を見て、<br>少し悪戯心が芽生えてくる。": "Thấy phản ứng của Kotono như thể không thể chịu đựng thêm được nữa,<br>trong lòng tôi chợt trỗi dậy chút tính xấu muốn trêu chọc.",
    "コトノ、お前は今、俺にどうされたいんだ？": "Kotono, bây giờ cậu muốn ta làm gì với cậu đây?",
    "ど、どうと申されても……<br>だ、旦那様と……そ、その……早くひとつになりたいです……": "N-Hỏi vậy thì……<br>T-Tại hạ muốn cùng Tướng công…… c-chuyện đó…… mau chóng hòa làm một ạ……",
    "それじゃわからないな。<br>どこをどんなふうにして欲しいのかもっとはっきり言ってくれないと……": "Nói thế thì sao ta biết được.<br>Cậu phải nói rõ hơn là muốn ta làm gì vào đâu chứ……",
    "は、はっきりとって申されましても……だ……旦那様の御立派なおちんちんで、<br>コトノのいやらしい割れ目を……つ、貫いてください……": "N-Nói rõ ra thì…… b-bằng dương vật vĩ đại của Tướng công,<br>xin ngài hãy…… đ-đâm xuyên qua khe dâm dật của Kotono đi ạ……",
    "コトノは顔中を真っ赤にしながら、卑猥な欲求を口にする。<br>自分の言葉に興奮したのか、秘処からまたいやらしい唾液が溢れてきた。": "Kotono đỏ bừng cả mặt khi thốt ra ham muốn dâm ô.<br>Có lẽ tự kích thích bởi lời nói của chính mình, nơi thầm kín lại rỉ ra dâm dịch ướt đẫm.",
    "その色欲にまみれた甘い淫蜜を亀頭に塗り付け、<br>彼女の要求に応える準備をすすめる。": "Tôi bôi dòng dâm mật ngọt ngào thấm đượm sắc dục đó lên quy đầu,<br>chuẩn bị đáp ứng thỉnh cầu của cô ấy.",
    "んんぅっ！　んっ……ふぁあぁぁぁぁぁぁ～～～～っ！": "Hừm u! Ưm…… phơ a a a a a a ～～～～!",
    "一気に奥まで挿入され、コトノは全身を痙攣させて歓びに震えた。<br>しっぽをピンと立てて、全身で悦んでいる。": "Bị đâm một cú lút cán vào tận bên trong, Kotono co giật toàn thân vì sung sướng.<br>Chiếc đuôi dựng đứng lên, toàn thân cô như đang hoan hỉ.",
    "ひぐぅっ♡　はっ、あっ、あぁぁぁぁぁぁ……っ♡<br>や、やはり自分の指でするのとは全然……違う……": "Hức u♡ Hả, a, a a a a a……♡<br>Q-Quả nhiên khác hẳn với tự làm bằng ngón tay……",
    "はぅ、あっ、あぁ……自分の指と、全然違うっ！<br>私の中、隅々まで、全部、旦那様のモノが、当たってます……♡": "Hà u, a, aa…… Khác hẳn với ngón tay mình!<br>Mọi ngóc ngách bên trong tại hạ đều bị đồ của Tướng công va chạm vào……♡",
    "はぁ、はぁ……お、お腹の奥まで、旦那様の温もりが伝わってきて……<br>す、すごく……心地いい……♡": "Hà, hà…… H-Hơi ấm của Tướng công truyền tận vào sâu trong bụng……<br>R-Rất…… sướng……♡",
    "これを……これをずっと、挿れて欲しくて堪らなかったんです……<br>毎晩、旦那様に、こうされるのを想像しながら自分で身体を慰めてました……": "Cái này…… Tại hạ đã khát khao được cắm cái này vào không chịu nổi nữa rồi……<br>Mỗi đêm tại hạ đều tưởng tượng cảnh được Tướng công làm thế này mà tự giải tỏa……",
    "これが発情期のせいなのかはわからないが、<br>いつも以上にコトノの膣肉が肉棒を咥え込むようにまとわりついてくる。": "Chẳng rõ có phải do mùa phát dục không,<br>nhưng thịt âm道 của Kotono quấn chặt lấy thanh thịt như muốn nuốt chửng hơn hẳn mọi khi.",
    "その旦那様のモノが、やっと私の中に……♡<br>ああっ、んっ……はぁぁぁっ……と、とても幸せな気分です……♡": "Thứ đó của Tướng công cuối cùng cũng ở trong người tại hạ……♡<br>Aa, ưm…… hà aa…… cảm thấy r-rất hạnh phúc ạ……♡",
    "あっ……あんっ♡　あっ……あぁっ……！<br>んっ……ぁあんっ……！　はぁぁっ……ぅうん……っ！": "A…… a ưm♡ A…… a aa……!<br>Ưm…… a ưm……! Hà aa…… ừm……!",
    "ひうっ！　あああっ、あっ、あっ……ぁあんっ！！♡<br>だ、旦那様の……熱いのが、奥まで当たって……き、気持ち……いぃ♡": "Hơ u! A aa, a, a…… a ưm!!♡<br>Thứ nóng rực của T-Tướng công…… chạm vào tận sâu bên trong…… s-sướng…… quá♡",
    "腰を突き出す度に、コトノの子宮口をグイグイと押し上げる。<br>その度に、コトノは耳としっぽを反応させて大きな喘ぎ声を上げる。": "Mỗi lần tôi thúc hông đều ráng sức đẩy tử cung Kotono lên.<br>Mỗi lần như thế tai và đuôi Kotono lại giật giật rồi thốt lên tiếng rên dâm mị.",
    "今日のコトノの秘処は、いつもよりグイグイと締め付けてくるみたいだった。<br>これも発情期の影響なのだろうか？　コトノに質問をぶつける。": "Chỗ thầm kín Kotono hôm nay co bóp siết chặt hơn hẳn mọi khi.<br>Liệu đây cũng là ảnh hưởng của mùa phát dục sao? Tôi lên tiếng hỏi Kotono.",
    "そ、そんなの分かんないですっ……！<br>でも私も、いつも以上に敏感に、なってて……あっ……ぁあんっ♡": "C-Chuyện đó tại hạ làm sao biết được chứ……!<br>Nhưng tại hạ cũng thấy nhạy cảm hơn hẳn mọi khi nữa…… a…… a ưm♡",
    "（やっ……！　やだ……本当に私の身体……ど、どうしちゃったんだろ？<br>お腹の奥から、次々といやらしい汁が……あふれ出てくる……）": "(Đừng……! Đừng mà…… Rốt cuộc cơ thể mình…… b-bị làm sao thế này?<br>Từ sâu trong bụng dâm dịch cứ liên tục…… trào ra ngoài……)",
    "あっ、あああっ！　気持ち……いいっ♡<br>今までで、一番……気持ちいいですっ♡": "A, a aa! Sướng…… quá♡<br>Từ trước tới giờ…… sướng nhất luôn đó ạ♡",
    "んんっ……あはぁっ♡　つ、突かれる度に、<br>全身にビリビリと刺激が走るみたいで……こ、こんなの……初めて……！": "Hừm…… a hà♡ M-Mỗi lần bị thúc vào,<br>toàn thân như có dòng điện xé dọc qua…… th-thế này…… lần đầu tiên luôn……!",
    "コトノは我を忘れるほどに感じている。<br>だが、その時、ある気配に感づいてしまう。": "Kotono sướng đến mức quên cả bản thân.<br>Nhưng đúng lúc đó, tôi chợt nhận ra có luồng khí tức đang tiến lại.",
    "え……？　だ、旦那様……？": "Hả……? T-Tướng công……?",
    "急に動きを止められて、コトノは戸惑った声を上げた。<br>非難するような目でこちらを振り返っている。": "Bị dừng lại đột ngột, Kotono thốt lên giọng ngơ ngác.<br>Cô ngoảnh lại nhìn tôi với ánh mắt như muốn trách móc.",
    "旦那様、そんないじわるしないでください……<br>私、もうおかしくなるくらい、気持ちよくて……": "Tướng công đừng xấu tính trêu tại hạ thế chứ……<br>Tại hạ đang sướng đến mức phát điên lên rồi……",
    "コトノを無視して耳を澄ます。<br>遠くから近付いてくるのは、たしかに足音と男たちの話し声だった。": "Tôi phớt lờ Kotono và tập trung lắng nghe.<br>Tiếng bước chân và tiếng trò chuyện của đàn ông quả thực đang từ xa tiến lại.",
    "え……誰か、来る……？": "Hả…… Có ai đến sao……?",
    "コトノもやっとその気配に気づいたらしい。<br>絶対に人が来ないと思っていたらしく、驚きと動揺で身体が強ばっている。": "Kotono dường như cũng vừa nhận ra luồng khí tức đó.<br>Cứ tưởng tuyệt đối không có ai tới nên cô giật mình kinh hãi làm cơ thể cứng đờ.",
    "この声……昼間、私が稽古つけた兵士たちです。<br>そうか、私が教えたことを復習するためにこんな夜更けに……": "Giọng này…… là các binh sĩ ban ngày tại hạ vừa huấn luyện.<br>Ra thế, họ đến đây đêm hôm thế này là để ôn lại bài học……",
    "旦那様……どうしましょう？": "Tướng công…… giờ sao đây ạ?",
    "追い払うしかないだろう。": "Chỉ có nước đuổi họ đi thôi.",
    "え？　でも、どうやって……": "Hả? Nhưng làm sao đuổi……",
    "んっく……！？　な、何をなさってるんです……！？<br>だ、旦那様……！？": "Hức……!? N-Ngài đang làm gì thế……!?<br>T-Tướng công……!?",
    "んっ……ぅうんっ……んっ……んんんっ……はぁっ……！": "Ưm…… ừm…… ưm…… hừm…… hà……!",
    "（だ、旦那様……こ、この状況が分かってないの！？<br>声出しちゃったら……み、見つかっちゃう状況なのに……！！）": "(T-Tướng công…… ngài không hiểu tình hình hiện tại sao!?<br>Nếu phát ra tiếng là…… s-sẽ bị phát hiện đấy……!!)",
    "コトノは声が漏れないように口を押え、必死に口を手で塞いでいる。<br>そんな必死な抵抗を他所に、容赦なくガシガシと激しく抽送を続ける。": "Kotono lấy tay bịt chặt miệng để tiếng rên không lọt ra ngoài.<br>Thế nhưng mặc cho cô kháng cự tuyệt vọng, tôi vẫn tàn nhẫn dồn dập nhấp hông mãnh liệt.",
    "んぐっ、んっ、んぐぐっ……！<br>あ、あっ、ひぅ、んんっ……！": "Hức, ưm, hức hức……!<br>A, a, hơ u, hừm……!",
    "んんんんっ……！　ぁああっ……ああああああぁぁぁぁ～～っ♡": "Hừm hừm……! A aa…… A a a a a a a ～～♡",
    "激しい突き上げにこらえきれなくなったのか、コトノの口から手が外れ、<br>訓練所の中に甘い嬌声が鳴り響いてしまう。": "Có lẽ không chịu nổi cú thúc dồn dập, tay Kotono tuột khỏi miệng,<br>tiếng rên kiều mị ngọt ngào vang vọng khắp huấn luyện sở.",
    "あんっ……あっ、あぁっ……んんんっ！　<br>やっ……んんっ……ぁああっ……んっ……ぁあんっ！": "A ưm…… a, aa…… hừm!<br>Đừng…… hừm…… a aa…… ưm…… a ưm!",
    "え！？　な、なんだ……？": "Hả!? C-Cái gì thế……?",
    "この声は、まさか……": "Tiếng này chẳng lẽ là……",
    "さすがに外にも聞こえたらしく、動揺している声が聞こえてくる。<br>それがどういう時に発せられる声かにも気づいたらしい。": "Có vẻ bên ngoài cũng nghe thấy nên vang lên những tiếng xôn xao dao動.<br>Họ dường như cũng nhận ra đó là âm thanh phát ra trong hoàn cảnh nào.",
    "えーと……<br>だ、誰か稽古中らしいな！": "À thì……<br>Hình như có ai đang luyện tập đấy!",
    "そ、そうだな！<br>邪魔しては悪い、今日はやめておくか！": "Đ-Đúng thế!<br>Làm phiền người ta thì không tốt, hôm nay về thôi!",
    "わざとらしく言い合い、兵士たちの気配は遠ざかっていった。": "Họ cố tình giả vờ đối đáp rồi khí tức các binh sĩ xa dần.",
    "ぅうんっ……はぁっ……はぁっ……はぁっ……はぁっ……": "Ừm…… hà…… hà…… hà…… hà……",
    "そこでやっと動きを止めると、コトノの体からグッタリと力が抜けた。": "Đến lúc đó tôi mới dừng lại, toàn thân Kotono lập tức bủn rủn mất hết sức lực.",
    "だ、旦那様……いくら何でも、やり方が手荒すぎ……です……<br>今の、絶対私だってバレてしまってますよ……": "T-Tướng công…… Dù gì thì cách làm của ngài cũng quá thô bạo rồi……<br>Vừa rồi nhất định họ đã biết là tại hạ rồi……",
    "兵士たちのあのよそよそしさはそうかもしれない。<br>手っ取り早く人払い出来るベストな選択だと思ったが……": "Thái độ gượng gạo của mấy gã binh sĩ đúng là như thế.<br>Ta cứ nghĩ đó là lựa chọn tốt nhất để đuổi người nhanh chóng cơ đấy……",
    "ど、どうしよう、明日からの訓練……<br>どんな顔で兵士たちに会えばいいのかしら……": "L-Làm sao đây, bài huấn luyện từ ngày mai……<br>Tại hạ biết mang mặt mũi nào gặp các binh sĩ đây……",
    "コトノは困った顔で考え込んでいるが、今は考えている時間はない。<br>またいつ誰が来るかわからないのだ。": "Kotono nhăn nhó trầm tư suy nghĩ, nhưng lúc này không có thời gian nghĩ ngợi nữa.<br>Chẳng biết bao giờ lại có ai tới đâu.",
    "とにかく、今はコトノの発情を早く鎮めることが最優先だろう。": "Tóm lại lúc này ưu tiên hàng đầu là giúp Kotono hạ hỏa mùa phát dục.",
    "あ……はい、お願いします……旦那様に早く鎮めてもらわないと、<br>私、またおかしくなっちゃいます……": "A…… vâng, nhờ Tướng công…… Nếu Tướng công không mau giúp giải tỏa,<br>tại hạ lại phát điên lên mất……",
    "ひゃううっ！　あんっ、ああっ、あっ、んぐ、あああっ♡<br>あ、さっきより……は、激しい……！": "Hơ uuu! A ưm, a aa, a, hức, a aa♡<br>A, m-mạnh hơn khi nãy nữa……!",
    "揺れるしっぽを掴みながら、再び獣のように激しく腰を振る。": "Vừa nắm lấy chiếc đuôi vẫy vùng, tôi vừa nhấp hông mãnh liệt như dã thú.",
    "ぁあんっ……あっ、あっ、あぁっ……はぁああぁ……！　<br>ぅうんっ……！　んっ……んぁああっ……あぁっ……ぁあはぁ……！": "A ưm…… a, a, aa…… hà a aa……!<br>Ừm……! Ưm…… ưm a aa…… aa…… a a hà……!",
    "コトノはさっきまで我慢していた分も発散させるように大きな声を上げ、<br>快感を貪るように自分から激しく腰を振ってくる。": "Kotono rên lớn như để giải tỏa nốt phần nín nhịn khi nãy,<br>cô ấy tự mình chủ động lắc hông dữ dội như tham khát khoái cảm.",
    "パンパンと、激しく肉が肉を打つ音が辺りに響く。<br>どんどん大きくなる音と共に、快感も増大していった。": "Tiếng phạch phạch do thịt va đập mãnh liệt vang vọng khắp xung quanh.<br>Cùng với tiếng động ngày càng lớn, khoái cảm cũng tăng dần lên.",
    "ああっ……お、奥にズンズンと当たって……き、気持ちいぃ……っ♡<br>あぁっ……ぁはぁっ……旦那様……私……気持ちいぃです……♡": "Aa…… Thúc rần rật vào tận sâu bên trong…… s-sướng quá……♡<br>Aa…… a hà…… Tướng công…… tại hạ…… sướng lắm……♡",
    "ぁあああっ……旦那様……私……も、もう……<br>が、我慢できそうにありません……イ……イっちゃいそう……！": "A a aa…… Tướng công…… tại hạ…… kh-không thể……<br>k-kiềm chế nổi nữa rồi…… L-Lên đỉnh mất thôi……!",
    "コトノの声が切迫していた。<br>その蜜壺も漏らしたように濡れて急激にキツくなってくる。": "Giọng Kotono trở nên dồn dập gấp giáp.<br>Huyệt mật của cô ấy ướt đẫm trào ra và đột ngột siết chặt lại.",
    "んぁああっ！　ぁああああぁ～～～～～～～っ♡": "Ưm a aa! A a a a a a ～～～～～～～♡",
    "激しく突き入れ、一番奥で射精した瞬間、コトノも同時に絶頂していた。": "Khoảnh khắc tôi dồn lực thúc lút cán bắn tinh vào tận sâu bên trong, Kotono cũng đồng thời chạm tới đỉnh điểm.",
    "はぁ、はぁ、はぁ……はぁ……<br>わ、私のお腹の中……旦那様の温かいので一杯……あ、あったかい……": "Hà, hà, hà…… hà……<br>B-Bên trong bụng tại hạ…… ngập tràn dòng tinh nóng hổi của Tướng công…… n-nóng quá……",
    "だ、旦那様……、あ、ありがとうございます……<br>い、今までした中で……い、一番……気持ちよかった……": "T-Tướng công…… c-cảm ơn ngài……<br>T-Trong những lần từ trước tới nay…… s-sướng nhất luôn……",
    "思う存分絶頂すると、コトノはぐったりと柱にもたれかかった。<br>まだ激しく肩で息を繰り返している。": "Sau khi lên đỉnh thỏa thích, Kotono rũ rượi dựa vào cột nhà.<br>Hai vai cô vẫn phập phồng thở dồn dập.",
    "はぁ……はぁっ……こ、このまま休ませてもらってもいいですか……？<br>ぜ、全身に力が入らなくて……はぁ……はぁ……はぁ……": "Hà…… hà…… Th-Cho phép tại hạ nghỉ ngơi thế này chút nhé……?<br>T-Toàn thân không còn chút sức lực nào nữa…… hà…… hà…… hà……",
    "どうやら発情の疼きは一旦収まったらしい。<br>コトノは柱に身体を預けながらも、満足した微笑みを浮かべていた。": "Có vẻ như sự nhói đau của mùa phát dục đã tạm thời lắng xuống.<br>Kotono dẫu tựa người vào cột nhà nhưng trên môi vẫn nở nụ cười mãn nguyện."
}

data_33 = {
    "数日後、訓練所に様子を見に行ってみると、<br>コトノはいつものように師範代として兵士たちに訓練を施していた。": "Mấy ngày sau, khi tôi đến huấn luyện sở xem tình hình,<br>Kotono vẫn đang làm trợ giảng huấn luyện các binh sĩ như mọi khi.",
    "コトノ、あれから調子はどうだ？": "Kotono, tình hình thế nào rồi?",
    "あ……旦那様。<br>あ、あの、外で話しましょうか。": "A…… Tướng công.<br>Ch-Chuyện đó, chúng ta ra ngoài nói nhé.",
    "コトノに腕を掴まれて、外に連れ出される。": "Tôi bị Kotono nắm lấy tay kéo ra bên ngoài.",
    "それで、あれから発情期のほうはもう大丈夫なのか？": "Thế nào, chuyện mùa phát dục từ dạo đó đã ổn chưa?",
    "はい。おかげさまでそっちはもう大丈夫だと思います。<br>ですが、ちょっとだけ問題が……": "Vâng. Nhờ có ngài mà chuyện đó đã ổn rồi ạ.<br>Nhưng lại có một chút vấn đề……",
    "問題？": "Vấn đề?",
    "その……旦那様とのあの激しい夜のことを思い出してしまうと、<br>発情していなくても身体が熱くなって……欲しく、なってしまって……": "Chuyện là…… Hễ nhớ lại đêm mãnh liệt đó cùng Tướng công,<br>dù không phải mùa phát dục nhưng cơ thể tại hạ lại nóng lên…… và lại thèm muốn……",
    "コトノは、もうまた発情してしまったかのように顔を真っ赤に染める。": "Kotono đỏ bừng mặt như thể cô lại vừa bước vào mùa phát dục.",
    "流石に……旦那様……１つお願いがあるんですが。": "Vì thế, Tướng công…… tại hạ có một thỉnh cầu.",
    "もしまた私の発情期が来てしまった時には、あの……<br>是非また、旦那様に抑えていただきたいと、思いまして……": "Nếu mùa phát dục của tại hạ lại tới nữa thì……<br>Tại hạ rất mong lại được Tướng công giúp giải tỏa……",
    "む、無理なお願いでしょうか？": "R-Yêu cầu này có quá đáng lắm không ạ?",
    "もう発情してるんじゃないかという色っぽい顔でお願いをされる。<br>そんな顔を見せられたら、次の発情期が待ち遠しくなってしまうのだった。": "Cô ấy đưa ra thỉnh cầu với gương mặt gợi cảm như thể đã vào mùa phát dục rồi.<br>Nhìn thấy gương mặt ấy, tôi cũng đâm ra nôm nốp ngóng chờ mùa phát dục tiếp theo của cô."
}

files = [
    ("hmr_10110100012", data_12),
    ("hmr_10110100013", data_13),
    ("hmr_10110100021", data_21),
    ("hmr_10110100022", data_22),
    ("hmr_10110100023", data_23),
    ("hmr_10110100031", data_31),
    ("hmr_10110100032", data_32),
    ("hmr_10110100033", data_33),
]

for folder, data in files:
    path = os.path.join(BASE_DIR, folder, "en.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
    print(f"Updated {folder}/en.json")

print("All 8 files updated successfully!")
